### ISSUE TITLE
请教怎么获取不同ver对应的addr

### ISSUE THREAD

**Issue by pxss** [AirEvan/SharpKey#1]
测试发现部分微信版本(如3.4.5.27)没有对应的addr，请问能教下怎么获取不同版本的addr吗？谢谢

**Comment by Ormicron** [comment]
项目之前都是使用笨办法手动调试的，难免出现小版本遗漏，目前是使用工具自动获取基址并手动添加的。获取基址可以参考:https://zhuanlan.zhihu.com/p/340276760
