### ISSUE TITLE
新版本不支持了

### ISSUE THREAD

**Issue by PureWaterSun** [AirEvan/SharpKey#2]
新版本不支持了

**Comment by Ormicron** [comment]
方便提供下你使用的版本号么

**Comment by PureWaterSun** [comment]
这是来自QQ邮箱的自动回复邮件。
 已收到！

**Comment by PureWaterSun** [comment]
3.7.0.30

**Comment by Ormicron** [comment]
这个版本验证是可以成功获取key的，参考https://github.com/Ormicron/Sharp-dumpkey/blob/main/padding.json

**Comment by PureWaterSun** [comment]
昨天还不行  -_-||  刚刚试了竟然可以了

**Comment by Ormicron** [comment]
啊...这....

**Comment by PureWaterSun** [comment]
这是来自QQ邮箱的自动回复邮件。
 已收到！
